name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Usa la versión de Python que prefieras

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pytest safety

      - name: Run the tests
        run: pytest test_game.py

      - name: Run safety
        run: safety check
